### PR TITLE
fix allowed calendarType in README.md

### PR DESCRIPTION
**Pull request by sturmenta**
the docs can be confusing

only this are the allowed calendar types

Screenshot 2023-07-06 at 11 04 51

### CODE REVIEW

**Comment by wojtekmaj** [comment]
You're looking at the docs for a newer version than the one you have installed.

**Comment by sturmenta** [comment]
@wojtekmaj `    "react-calendar": "^4.3.0"`

**Comment by sturmenta** [comment]
Screenshot 2023-07-06 at 11 52 30
Screenshot 2023-07-06 at 11 52 01

you sure?

**Comment by wojtekmaj** [comment]
Absolutely. React-Calendar is under constant development and the documentation on GitHub is for whatever is on main branch, not necessarily released.

Every release ships with its own README, which you can also read on npmjs.com.

**Pull request closed without merging**
