### PR TITLE
Don't call onActiveStartDateChange, onViewChange, onChange if the values didn't change

### LINKED ISSUE #343: onActiveStartDateChange gets Triggered after onClickDay since 3.x
onActiveStartDateChange
`Function called when the user navigates from one view to another using previous/next button.`

After updating to 3.x we started getting the issue that onActiveStartDateChange is called even if you just click on a day in month view.

This issue is blocking us from upgrading to 3.x

### PR DESCRIPTION
**Pull request by wojtekmaj**
Fixes #343

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@juspky Can you try this branch in your project and verify if it works as expected for you?

**Comment by juspky** [comment]
sure, I'll to do it tomorrow when I'm at work again.

**Comment by juspky** [comment]
The issue still occurs to me
[https://gofile.io/?c=LIiF43](url)

you can reproduce the issue with this code and selecting a day

` <Calendar
                showFixedNumberOfWeeks
                minDetail="year"
                onActiveStartDateChange={() => console.log("onActiveStartDateChange")}
              />`

**Comment by strap8** [comment]
Same thing is happening for me.

**Comment by wojtekmaj** [comment]
Should be okay now, added better tests. Sorry about that!

**Pull request merged**
