### PR TITLE
prioritize activeStartDate over value

### LINKED ISSUE #43: Changing activeStartDate does not change calendar view
Hi,

I'm trying to use the library with a custom external navigation.
So on click on next/prev of my custom navigation I update the prop "activeStartDate" but the calendar not change.

I saw that the "activeStartDate" in the state of Calendar component is not updated by props.

### PR DESCRIPTION
**Pull request by balazsorban44**
potentially fixes #43

### CODE REVIEW

**Comment by klapec** [comment]
@wojtekmaj Any chance this could be merged in, even behind an option? I can confirm that it works.

**Comment by wojtekmaj** [comment]
It's a breaking change so I need to figure out how to implement this without destroying everyone else's workflow.

**Comment by klapec** [comment]
> It's a breaking change so I need to figure out how to implement this without destroying everyone else's workflow.

Understandable, thanks! 👍

**Comment by wojtekmaj** [comment]
Thank you for your contribution. It is now added to 3.x branch.

See #216 for implementation roadmap & news.

**Pull request closed without merging**
