### PR TITLE
Expose events in onChange, onClick* functions

### LINKED ISSUE #258: Expose event to onChange/onClickDay
**Problem I have:** 
When i click the calendar, i would trigger sibling input onBlur func.

**Some thoughts:** 
So if i can get access to `event` and use `event.stopPropagation` in onClickDay,
that would be awesome. 
Thanks in advance.

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #258

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@DDDDDanica Can you try this in your project and give feedback?

**Comment by cibulka** [comment]
Hello @wojtekmaj and thanks for an awesome library!

Is is just me though or the events are not passed to callback functions (as this commit should have changed)? 

I hope I'm not missing something. Thank you!

## Reproduction

[codesandbox.io](https://codesandbox.io/s/staging-brook-jgbzx?fontsize=14&hidenavigation=1&theme=dark)

- react: 16.12.0
- react-calendar: 2.19.2

**Comment by teerzo** [comment]
event changes added into v3.0.0
i made the same mistake trying to access them on an older version

**Comment by DDDDDanica** [comment]
> Hello @wojtekmaj and thanks for an awesome library!
> 
> Is is just me though or the events are not passed to callback functions (as this commit should have changed)?
> 
> I hope I'm not missing something. Thank you!
> 
> ## Reproduction
> [codesandbox.io](https://codesandbox.io/s/staging-brook-jgbzx?fontsize=14&hidenavigation=1&theme=dark)
> 
> * react: 16.12.0
> * react-calendar: 2.19.2

hey @cibulka You are using "2.19.2" version... i think that's the reason...

**Comment by Nord18** [comment]
I using 3.0.1 version, but event still undefined

**Comment by VGLoic** [comment]
Using 3.1.0 version, but go `undefined` too for the second arg of `onChange`

Reproduction:

codesandbox: https://codesandbox.io/s/react-calendar-events-n0ibt?file=/src/App.js
- react: 16.13.1
- react-calendar: 3.1.0

**Comment by wojtekmaj** [comment]
Thanks @VGLoic, fixed that in https://github.com/wojtekmaj/react-calendar/pull/388.

**Pull request merged**
