### PR TITLE
Fix wrong margin calculation with RTL - fixes #222

### LINKED ISSUE #222: wrong inline style calculation with RTL layout
Hi, 

When the layout is based on RTL (right-to-left) & `showNeighboringMonth={false}` the calculation of `margin` of the first item is hard coded to **left**, this makes the calendar looks like:

image

instead of that it should be `margin-right`.

### PR DESCRIPTION
**Pull request by felixmosh**
This PR fixes #222

### CODE REVIEW

**Comment by felixmosh** [comment]
Ping?

**Comment by wojtekmaj** [comment]
Hi, thanks for this contribution. I really appreciate it!

I'm wondering if this is not a solution for a problem I could have not created in the first place. For example, what if I created empty divs in place of days that should not be displayed? Or what if I used `justify-content: flex-end` to push things instead?

**Comment by felixmosh** [comment]
I've thought about it, `justify-content` solution will break case where last day of the month is at the begining of the week, then the days will align improperly.

The solution with empty cells will work, but it is a wast of dom elements.

**Comment by felixmosh** [comment]
Any updates regarding this PR?

**Comment by wojtekmaj** [comment]
Margin-inline-start is the way! Will reimplement this. Yeah, I know it's been years but... 😅

**Pull request closed without merging**
