### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by wojtekmaj**
Based on awesome work of third774 in wojtekmaj/react-date-picker#18 - whole description of it applies.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hey @third774, would you mind having a look? I did it based on your PR in react-date-picker and react-calendar is one of its dependency.

Also, if you have any interesting reads on what are the benefits, how to do it properly and most importantly how to test it, I'd greatly appreciate it! Of course if that's too much of a trouble I'll stick [to what I'm reading](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) :)

**Comment by third774** [comment]
This works for the `Calendar` component, however the `MonthView`, `YearView`, `DecadeView`, and `CenturyView` components are missing their types. Will try to put together an example of how to do those soon.

**Comment by third774** [comment]
Does this interface look correct for those other components? It looks like `activeStartDate` is the only mandatory prop (I get an error if I don't provide it).

```ts
/// <reference types="react" />

type Detail = "month" | "year" | "decade" | "century"
type DateCallback = (date: Date) => void

declare module "react-calendar" {
  export default function Calendar(props: CalendarProps): JSX.Element;

  export interface CalendarProps {
    calendarType?: "US" | "ISO 8601";
    className?: string | string[];
    locale?: string;
    maxDate?: Date;
    maxDetail?: Detail;
    minDate?: Date;
    minDetail?: Detail;
    next2Label?: string | React.ReactElement<any>;
    nextLabel?: string | React.ReactElement<any>;
    onChange?: DateCallback;
    onClickDay?: DateCallback;
    onClickDecade?: DateCallback;
    onClickMonth?: DateCallback;
    onClickYear?: DateCallback;
    prev2Label?: string | React.ReactElement<any>;
    prevLabel?: string | React.ReactElement<any>;
    renderChildren?: (props: CalendarRenderChildrenProps) => JSX.Element | null;
    returnValue?: "start" | "end" | "range";
    showNavigation?: boolean;
    showNeighboringMonth?: boolean;
    showWeekNumbers?: boolean;
    value?: Date | Date[];
    view?: Detail;
  }

  export interface CalendarRenderChildrenProps {
    date: Date;
    view: Detail
  }

  export function MonthView(props: DetailViewProps): JSX.Element;
  export function YearView(props: DetailViewProps): JSX.Element;
  export function DecadeView(props: DetailViewProps): JSX.Element;
  export function CenturyView(props: DetailViewProps): JSX.Element;

  export interface DetailViewProps {
    activeStartDate: Date;
    maxDate?: Date;
    minDate?: Date;
    onClick?: DateCallback;
    renderChildren?: (props: CalendarRenderChildrenProps) => JSX.Element | null;
    value?: Date | Date[];
  }
}

```

**Comment by third774** [comment]
PR https://github.com/wojtekmaj/react-calendar/pull/8 created! 🤜💥🤛

**Comment by wojtekmaj** [comment]
Can't quantify how grateful I am! Thanks @third774 !

**Pull request merged**
